### ISSUE TITLE
It isn't creating the channel, but has connected to query.

### ISSUE THREAD

**Issue by NixBoy** [Xuxe/TS3-Channel-Creator#1]
If you connect, you can see that it fetches you're unique id.
But when you put all channel info in, it doesn't create one.
Please help.

I have PHP7, you said that you didn't know if it supports PHP7.. But when I downgraded to PHP 5.6 it didn't work at all. didn't even fetch my unique id.

**Comment by NixBoy** [comment]
// I edited the code, got it working.
Thanks anyway.

**Comment by Xuxe** [comment]
@NixBoy - feel free to provide a PR.  👍 

I think the issue could be the rewrite of the PHP-Framework; the Framework should be updated i don't know how the old framework work with the new TS3-Server versions. 

I don't wanted to support the project active again, may i fix it if no PR is provided.
